### ISSUE TITLE
Document refreshInterval changes

### ISSUE THREAD

**Issue by senorprogrammer** [wtfutil/wtfdocs#136]
Per this PR https://github.com/wtfutil/wtf/pull/1120/files

**Comment by senorprogrammer** [comment]
Don't do this yet. I've reverted the original PR due to the issue described here https://github.com/wtfutil/wtf/pull/1120

**Comment by trimble** [comment]
Is this good to go now that PR #1139 is merged?

**Comment by senorprogrammer** [comment]
Yes, for sure.
