### ISSUE TITLE
Power module dependencies

### ISSUE THREAD

**Issue by pliski** [wtfutil/wtfdocs#162]
I spent some time understanding why the power module wouldn't work.

I figured out that the module relies on an external command that needs to be installed in the system; this command varies depending on the OS.

I think that mentioning those dependencies on the documentation will save users some time and frustration.

**Comment by pliski** [comment]
I proposed PR #163 to address this issue.

**Comment by senorprogrammer** [comment]
Fixed via https://github.com/wtfutil/wtfdocs/pull/163
