### ISSUE TITLE
Modules sidebar is broken

### ISSUE THREAD

**Issue by spl** [wtfutil/wtfdocs#49]
It looks like 86e433c9b835a1cf097f774de6ecdc4bfaf3721a broke the Modules list in the sidebar. For example, see the following, in which it the list of modules is missing:

* https://wtfutil.com/modules/github/
  - https://github.com/wtfutil/wtfdocs/commit/86e433c9b835a1cf097f774de6ecdc4bfaf3721a#diff-d492eeadfcf67bc5923d0e0a333d5dea
* https://wtfutil.com/modules/opsgenie/
  - https://github.com/wtfutil/wtfdocs/commit/86e433c9b835a1cf097f774de6ecdc4bfaf3721a#diff-db2c26e7df517a72f10f646592e2b25e

**Comment by senorprogrammer** [comment]
Thanks for reporting this. Should be fixed now.
