### ISSUE TITLE
Add simple social meta tags

### ISSUE THREAD

**Issue by Arteneko** [wtfutil/wtfdocs#6]
This would allow to give a short description/title as social card embed, e.g. on social networks such as discord.

**Comment by senorprogrammer** [comment]
Do you have a pointer to an example of this?

**Comment by IvanDelsinne** [comment]
As an example, [this page](view-source:https://docs.artemix.org/sysadmin/wireguard-management/) have a `description` and `author` tags, producing the following result.

![](https://pix.watch/PwiRr1/FmEAPL.png)

Another solution would be to also add tags following [http://ogp.me/](http://ogp.me/).

**Comment by senorprogrammer** [comment]
Cool, thanks for the info!
