### ISSUE TITLE
Docs on how to uninstall?

### ISSUE THREAD

**Issue by maxbeizer** [wtfutil/wtfdocs#8]
Is there any information on how to uninstall wtf? I'm wary of installing anything that doesn't have a clear back out plan.

**Comment by senorprogrammer** [comment]
Excellent point. In the meantime `make install` just installs a single binary. So you can `which wtf` that and then `rm` the result. If you've run the binary you'll also want to remove the config in `~/.config/wtf`. Other than that, nothing else is changed.
