### ISSUE TITLE
Add documentation for gCal `showEndTime` setting

### ISSUE THREAD

**Issue by senorprogrammer** [wtfutil/wtfdocs#88]
https://github.com/wtfutil/wtf/pull/877/files#diff-6e1bcc7ca6a581fd5c6339d18d5d04a7R38

**Comment by Tdnshah** [comment]
Ill be adding the dcoumentation for this

**Comment by Tdnshah** [comment]
@senorprogrammer looking at u r reaction would like to ask if i picked the wrong issue is it so?

**Comment by senorprogrammer** [comment]
No, if you want to do this issue, that would be great.

**Comment by senorprogrammer** [comment]
Done
